# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0032212edbea244a63c61bd926888983d101cb476cbd99aaf7b0b5c8f97dc7a1e2468ecd502004ebc0ce3b26f13d41d0b312708a2b2032c052e8c0495eeb5895

test:
  secret_key_base: aceed34df5e907a6e08487f46389aa494430476c81501d9b29e2463c05aca70f875eb7eefd990385f94538ec2f3be93b7a454e71b4ac08daae1537e15c5a3266

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
